name: this is for terraform

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4  

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6 

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform apply -auto-approve
        env:
         TF_VAR_credentials: ${{ secrets.SERVICE_KEY }}
          
# testing


